// const swaggerAutogen = require('swagger-autogen')()

// const outputFile = './swagger_output.json'
// // const endpointsFiles = ['./api/routes/index.js']
// const endpointsFiles = ['index.js']

// swaggerAutogen(outputFile, endpointsFiles)

const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
   
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    
        
    }


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})